// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(in *jlexer.Lexer, out *UpdateSubscriptionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "service_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceName = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(out *jwriter.Writer, in UpdateSubscriptionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServiceName))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.String(string(in.StartDate))
	}
	if in.EndDate != "" {
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.String(string(in.EndDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateSubscriptionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateSubscriptionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateSubscriptionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateSubscriptionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(in *jlexer.Lexer, out *SubscriptionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "service_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceName = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(out *jwriter.Writer, in SubscriptionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServiceName))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.String(string(in.StartDate))
	}
	if in.EndDate != "" {
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.String(string(in.EndDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubscriptionDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubscriptionDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubscriptionDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubscriptionDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp1(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(in *jlexer.Lexer, out *ReadSubscriptionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "service_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceName = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(out *jwriter.Writer, in ReadSubscriptionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServiceName))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.String(string(in.StartDate))
	}
	if in.EndDate != "" {
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.String(string(in.EndDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReadSubscriptionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReadSubscriptionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReadSubscriptionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReadSubscriptionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp2(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(in *jlexer.Lexer, out *ListSubscriptionsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subscriptions":
			if in.IsNull() {
				in.Skip()
				out.Subscriptions = nil
			} else {
				in.Delim('[')
				if out.Subscriptions == nil {
					if !in.IsDelim(']') {
						out.Subscriptions = make([]SubscriptionDTO, 0, 0)
					} else {
						out.Subscriptions = []SubscriptionDTO{}
					}
				} else {
					out.Subscriptions = (out.Subscriptions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 SubscriptionDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Subscriptions = append(out.Subscriptions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(out *jwriter.Writer, in ListSubscriptionsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subscriptions\":"
		out.RawString(prefix[1:])
		if in.Subscriptions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Subscriptions {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListSubscriptionsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListSubscriptionsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListSubscriptionsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListSubscriptionsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp3(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(in *jlexer.Lexer, out *ErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(out *jwriter.Writer, in ErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp4(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(in *jlexer.Lexer, out *CreateSubscriptionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subscription_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubscriptionID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(out *jwriter.Writer, in CreateSubscriptionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subscription_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SubscriptionID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSubscriptionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSubscriptionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSubscriptionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSubscriptionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp5(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(in *jlexer.Lexer, out *CreateSubscriptionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "service_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ServiceName = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "start_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartDate = string(in.String())
			}
		case "end_date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndDate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(out *jwriter.Writer, in CreateSubscriptionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServiceName))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int(int(in.Price))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.String(string(in.StartDate))
	}
	if in.EndDate != "" {
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.String(string(in.EndDate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSubscriptionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSubscriptionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSubscriptionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSubscriptionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp6(l, v)
}
func easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(in *jlexer.Lexer, out *CalcTotalCostResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "total_cost":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalCost = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(out *jwriter.Writer, in CalcTotalCostResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"total_cost\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TotalCost))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CalcTotalCostResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CalcTotalCostResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson18daaca9EncodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CalcTotalCostResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CalcTotalCostResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson18daaca9DecodeGithubComEffectiveMobileTestTask28052026InternalTransportHttp7(l, v)
}
