// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  http

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CalcTotalCostResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CalcTotalCostResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CalcTotalCostResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CalcTotalCostResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CalcTotalCostResponse *CalcTotalCostResponse

func ( CreateSubscriptionRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateSubscriptionRequest ) UnmarshalJSON([]byte) error { return nil }
func ( CreateSubscriptionRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateSubscriptionRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateSubscriptionRequest *CreateSubscriptionRequest

func ( CreateSubscriptionResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateSubscriptionResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CreateSubscriptionResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateSubscriptionResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateSubscriptionResponse *CreateSubscriptionResponse

func ( ListSubscriptionsResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ListSubscriptionsResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ListSubscriptionsResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ListSubscriptionsResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ListSubscriptionsResponse *ListSubscriptionsResponse

func ( ReadSubscriptionResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReadSubscriptionResponse ) UnmarshalJSON([]byte) error { return nil }
func ( ReadSubscriptionResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReadSubscriptionResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReadSubscriptionResponse *ReadSubscriptionResponse

func ( SubscriptionDTO ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SubscriptionDTO ) UnmarshalJSON([]byte) error { return nil }
func ( SubscriptionDTO ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SubscriptionDTO ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubscriptionDTO *SubscriptionDTO

func ( UpdateSubscriptionRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UpdateSubscriptionRequest ) UnmarshalJSON([]byte) error { return nil }
func ( UpdateSubscriptionRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UpdateSubscriptionRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdateSubscriptionRequest *UpdateSubscriptionRequest
